# https://huggingface.co/t5-large
model_name_or_path: ${CACHE_DIR}/models/google/flan-t5-small # google/flan-t5-small
name: flan-t5-small

model:
  _target_: transformers.AutoModelForSeq2SeqLM.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}

tokenizer_kwargs:
  padding: max_length
  truncation: true
  return_tensors: pt
