defaults:
  - flan_t5_default
  - _self_

eval_dict_tta: false
eval_dict: true
profile: false

batch_size: 4
num_workers: 0

dict_feature_extractor: paraphrase-MiniLM-L6-v2 # sentenceTransformer: https://huggingface.co/sentence-transformers


version: null

lr: 5e-6

# device configurations
dict_feature_extractor_device: cuda
dict_mapping_device: cuda
task_vector_device: cuda
forward_devices: cuda
