name: super_glue-cb

datasets:
  _target_: datasets.load_dataset
  path: super_glue
  name: cb

preprocessor:
  _target_: src.tasks.super_glue.cb
  template_file: super_glue_v0/cb.json

map_kwargs:
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
