name: super_glue-wic

datasets:
  _target_: datasets.load_dataset
  path: super_glue
  name: wic

preprocessor:
  _target_: src.tasks.super_glue.wic
  template_file: super_glue_v0/wic.json

map_kwargs:
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
