name: super_glue-boolq

datasets:
  _target_: datasets.load_dataset
  path: super_glue
  name: boolq

preprocessor:
  _target_: src.tasks.super_glue.boolq
  template_file: super_glue_v0/boolq.json

map_kwargs:
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
